ARG BASE_IMAGE
FROM ${BASE_IMAGE}

COPY install/ /usr/share/nginx/html/
# Same file as meshsat.net's, one source to renew (MESHSAT-1186)
COPY site/static/.well-known/security.txt /usr/share/nginx/html/.well-known/security.txt
COPY nginx-install.conf /etc/nginx/nginx.conf
